# Linear regression using PyTorch built-ins

###1. First Step is to import neural network packages from **pytorch**

In [0]:
import torch.nn as nn
import torch

###2. Now we add Input and target values 

In [0]:
# Input (temp, rainfall, humidity)
inputs = torch.tensor([[73., 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]])
                  

# Targets (apples, oranges)
targets = torch.tensor([[56., 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]])
                   

*Validating*

In [0]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

*Dataset and DataLoader*

###3. To use Dataset for wrapping we import TensorDataset from pytorch utilities for data

In [0]:
 from torch.utils.data import TensorDataset

*Defining Dataset*

In [0]:
train_ds=TensorDataset(inputs,targets)

*Checking output for first 3 values*

In [0]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

###4. Now we import dataloader from pytorch utilities for data

In [0]:
from torch.utils.data import DataLoader 

*Defining DataLoader*

In [0]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

*Verifying output of DataLoader*

In [0]:
i=1
for xb,yb in train_dl:
  print(xb)
  print(yb)
  print("This is batch no.: {}".format(i))
  print('\n')
  i=i+1

tensor([[ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 81., 101.]])
This is batch no.: 1


tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.],
        [ 22.,  37.]])
This is batch no.: 2


tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])
This is batch no.: 3




###5. Now we need to define a Linear Regression Model using Neural Network Libraries 

In [0]:
model=nn.Linear(3,2)

*Randomized weights and bias*

In [0]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3980, -0.3980,  0.1916],
        [ 0.2686,  0.1345,  0.1055]], requires_grad=True)
Parameter containing:
tensor([-0.4936, -0.2683], requires_grad=True)


*Directly listing through .parameters method of nn*

In [0]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3980, -0.3980,  0.1916],
         [ 0.2686,  0.1345,  0.1055]], requires_grad=True),
 Parameter containing:
 tensor([-0.4936, -0.2683], requires_grad=True)]

*Generating predictions*

In [0]:
preds=model(inputs)
preds

tensor([[10.1287, 32.8820],
        [12.9571, 42.7550],
        [-8.0941, 47.2342],
        [30.0730, 36.8100],
        [ 2.1672, 38.5552],
        [10.1287, 32.8820],
        [12.9571, 42.7550],
        [-8.0941, 47.2342],
        [30.0730, 36.8100],
        [ 2.1672, 38.5552],
        [10.1287, 32.8820],
        [12.9571, 42.7550],
        [-8.0941, 47.2342],
        [30.0730, 36.8100],
        [ 2.1672, 38.5552]], grad_fn=<AddmmBackward>)

###6. Now we need to set up a loss function so the model realizes its mistakes

*importing functional library of neural network containing builtin loss functions*

In [0]:
import torch.nn.functional as F

*Defining loss fn*

In [0]:
loss_fn=F.mse_loss

*Computing loss for predictions*

In [0]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(5171.6743, grad_fn=<MseLossBackward>)


###7. Next step would be to set up an optimizer that corrects our mistakes in weight and bias values

*Defining Optimizer: stochastic gradient descent used*

In [0]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

These two will be used when creating a function for training not using here as no iteration mechanism is specified:
>loss.backward()
>>This computes gradients

> opt.step()
>> This updates parameters using gradients

>opt.zero_grad()
>>Resets gradients to zero





###8. The final step would be to train the model using multiple such iterations(epochs)

*Defining Function for Training*

In [0]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1)%10==0:
      print('Epoch [{}/{}],Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))
#loss.item returns the actual value stored in the loss tensor.

*training model for 100 epochs*

In [0]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100],Loss: 5.7880
Epoch [20/100],Loss: 4.3207
Epoch [30/100],Loss: 8.3599
Epoch [40/100],Loss: 5.4171
Epoch [50/100],Loss: 7.7533
Epoch [60/100],Loss: 5.0141
Epoch [70/100],Loss: 4.6030
Epoch [80/100],Loss: 2.7764
Epoch [90/100],Loss: 4.3042
Epoch [100/100],Loss: 3.7544
