In [0]:
import torch

In [0]:
t1=torch.tensor(4.)


In [0]:
t1

tensor(4.)

In [0]:
t1.dtype

torch.float32

In [0]:
x=torch.tensor([[73.,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]])

In [0]:
x.dtype

torch.float32

In [0]:
import numpy as np

In [0]:
y=np.array([[56.,70],
          [81,101],
          [119,133],
          [22,37],
          [103,119]])

In [0]:
y.dtype

dtype('float64')

In [0]:
targets=torch.from_numpy(y)

In [0]:
preds=x

In [0]:
print(x)
print(y)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [0]:
print(preds)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]], dtype=torch.float64)


In [0]:
#Linear Regression Model

In [0]:
# here 3 signifies number of components that effect the model for every statement
# 2 signifies number of result each row leads to
w=torch.randn(2,3, requires_grad=True)

In [0]:
# 2 signifies number of result each row leads to
b=torch.randn(2, requires_grad=True)

In [0]:
#Generate model
def model(a):
  return a @ w.t() +  b

In [0]:
#Generate Predictions
pred=model(preds)
print(pred)

tensor([[132.8584, 125.0908],
        [176.1249, 174.7035],
        [227.6122, 211.9179],
        [111.8783,  91.6302],
        [180.3291, 192.0333]], grad_fn=<AddBackward0>)


In [0]:
print(preds)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [0]:
#Loss function
diff=(pred-targets)

In [0]:
print(diff)

tensor([[ 76.8584,  55.0908],
        [ 95.1249,  73.7035],
        [108.6122,  78.9179],
        [ 89.8783,  54.6302],
        [ 77.3291,  73.0333]], dtype=torch.float64, grad_fn=<SubBackward0>)


In [0]:
torch.sum(diff*diff)/diff.numel()

tensor(6382.4050, dtype=torch.float64, grad_fn=<DivBackward0>)

In [0]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [0]:
loss=mse(pred,targets)
loss.backward()

In [0]:
print w

SyntaxError: ignored

In [0]:
print(w)

tensor([[ 0.3904,  1.2193,  0.5064],
        [-0.0433,  0.9892,  1.4104]], requires_grad=True)


In [0]:
print(w.grad)

tensor([[7643.9189, 7872.5811, 4886.1904],
        [5641.2168, 6022.4580, 3759.3633]])


In [0]:
#Optimization Algorithm
#As slope is positive here->>>
#We need to decrease the weight

with torch.no_grad():
  w-=w.grad*1e-5

In [0]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [79]:
#Creating an automated model
#for 100 Epochs
for i in range(100):
  pred=model(preds)
  loss=mse(pred,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()
  if i%10==0:
    print('epoch:',i)
    print('loss:',loss)

epoch: 0
loss: tensor(10.2483, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 10
loss: tensor(9.9720, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 20
loss: tensor(9.7123, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 30
loss: tensor(9.4677, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 40
loss: tensor(9.2366, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 50
loss: tensor(9.0176, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 60
loss: tensor(8.8097, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 70
loss: tensor(8.6118, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 80
loss: tensor(8.4229, dtype=torch.float64, grad_fn=<DivBackward0>)
epoch: 90
loss: tensor(8.2423, dtype=torch.float64, grad_fn=<DivBackward0>)
