<a href="https://colab.research.google.com/github/Pranaviate/MachineLearningNotebooks/blob/master/PyTor_Assgn1_NewFns_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PYTORCH ASSIGNMENT-1: TRYING OUT NEW FUNCTONS

*firstly importing torch*

In [0]:
import torch

Function 1:
>torch.linspace
>>Creates a torch 1D equally spaced tensor from `start` to `end`
>>>torch.linspace(`start`,`end`)




>>default is: 100 steps





In [0]:
torch.linspace(1,10)

tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

In [0]:
torch.linspace(1,10,19)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000])

Function 2:
>torch.eye
>>Creates a torch 2D tensor with zero diagonals 
>>1.   `n` as number of rows
>>2.   `m` as number of columns
>>>torch.eye(`n`,`m`)



>>if only `m` is defined then it creates a square 2D tensor of `m * m `


In [0]:
torch.eye(5,9)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [0]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Function 3:
>torch.full
>> returns a tensor of `size` with values filled with `fill_value`
>>>torch.full(`size=(x,x)`,`fill_value=x`)



>>size can be 'list' or a 'tuple'

In [0]:
torch.full(size=(5,3),fill_value=8)

/pytorch/aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [0]:
torch.full(size=(5,3),fill_value=8, dtype=float)

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]], dtype=torch.float64)

In [0]:
torch.full((5,4),7)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])

In [0]:
torch.full((5,4),7,float)

TypeError: ignored

The above argument works as `torch.full((5,4),7)` but shows an error when float is added for dtype property in the form `torch.full((5,4),7,float)`, this is because when we do not mention the properties by explicitly declaring them 
eg- 'size=5' then the function follows the default argument lineup for the functions

> The default arguments were in right order till the 'fill_value' but had other arguments in line than the dtype argument next




Hence the error
>A corrective solution is given below


In [0]:
torch.full((5,4),7,dtype=float)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]], dtype=torch.float64)

Function 4:
>torch.cat
>> concatenates 2 or more tensors into one tensor
>>>here `a` and `b ` are tensors to be joined, 
>>>`torch.cat((a,b))`




>>Default Dimension  is= 0

In [0]:
a=torch.tensor([[2,3,4,5],[7,5,3,2]])
b=torch.tensor([[5,6,8,9],[5,0,3,4]])
torch.cat((a,b))

tensor([[2, 3, 4, 5],
        [7, 5, 3, 2],
        [5, 6, 8, 9],
        [5, 0, 3, 4]])

In [0]:
torch.cat((a,b),dim=1)

tensor([[2, 3, 4, 5, 5, 6, 8, 9],
        [7, 5, 3, 2, 5, 0, 3, 4]])

In [0]:
torch.cat((a,b),dim=2)

IndexError: ignored

Here we see an error because the dimension should be either equal or less than the given tensor dimensions

In [0]:
torch.cat((a,b),dim=-1)

tensor([[2, 3, 4, 5, 5, 6, 8, 9],
        [7, 5, 3, 2, 5, 0, 3, 4]])

In [0]:
torch.cat((a,b),dim=0)

tensor([[2, 3, 4, 5],
        [7, 5, 3, 2],
        [5, 6, 8, 9],
        [5, 0, 3, 4]])

Function 5:
>torch.take
>>it returns a tensor with elements of input tensor at the given indices, here `input_tensor` is the tensor to be worked on and `torch.tensor([indices])` is the format for output tensor with given indices values
>>> torch.take(`input_tensor,torch.tensor([indices])`)

In [0]:
torch.take(a,torch.tensor([2]))

tensor([4])

In [0]:
torch.take(a,torch.tensor([2,3]))

tensor([4, 5])

In [0]:
torch.take(a,torch.tensor([2,6]))

tensor([4, 3])

Here the indices number is counted line wise and not in the form of matrice format
> hence for a 3*3 matrix a value a `(2,2)` will be counted `5` in indices